version: '3'
services:
  postgres-main:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_DB: launchday
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: launchdayPassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5000:5432'
  postgres-shadow:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_DB: launchday-shadow
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: launchdayPassword
    volumes:
      - postgres-shadow:/var/lib/postgresql/data
    ports:
      - '6000:5432'
volumes:
  postgres: dev-db-data/main
  postgres-shadow: dev-db-data/shadow
