-- CreateEnum
CREATE TYPE "UserOnboardingSegment" AS ENUM ('INDIVIDUAL_ARTIST', 'ARTIST_MANAGER', 'LABEL_MANAGER', 'LABEL_EMPLOYEE', 'MARKETING_COORDINATOR', 'PUBLICIST', 'SOCIAL_MEDIA_MANAGER', 'UPDATE_STATUS', 'UPDATE_DATE');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "segment" "UserOnboardingSegment";
