name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn build
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://notarealDb
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn test
