name: First cron job
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: run job
        run: |
          curl --request POST \
          --url 'https://launchday-postgres.herokuapp.com/api/jobs/reminders' \
          --header 'Authorization: Bearer ${{ secrets.CRON_JOB_KEY }}'
